### ISSUE TITLE
ImportError: No module named 'manager'

### ISSUE THREAD

**Issue by srikanth148** [swisscom/cleanerversion#133]
File "/usr/local/lib/python3.4/dist-packages/simple_history/models.py", line 8, in <module>
    from manager import HistoryDescriptor
ImportError: No module named 'manager'

I am getting this error while starting server

**Comment by brki** [comment]
Hi @srikanth148 I think you created this issue for the wrong project.  Perhaps you were looking for https://github.com/treyhunner/django-simple-history ?

**Comment by srikanth148** [comment]
I am sorry , the error is "ImportError: cannot import name 'ReverseSingleRelatedObjectDescriptor' "

**Comment by brki** [comment]
@srikanth148 a few questions:
* how did you install CleanerVersion?
* can you provide a small code sample that allows reproducing the problem?
* can you provide the full exception details (message + stack trace)?

**Comment by srikanth148** [comment]
I used pip to install CleanerVersin, Django version - 1.10.1
![screenshot from 2017-03-02 15 33 49](https://cloud.githubusercontent.com/assets/26059420/23502382/b0d23f66-ff5d-11e6-997e-a2922b630156.png)

Models
```
from django.db import models
from versions.models import Versionable, VersionedManyToManyField, VersionedForeignKey

class Person(Versionable):
    user_id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=256)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)

```

views
```
def create_record(request):
	Person.objects.create(email = 'test1@test.com', first_name = 'test1',
							 last_name = 'test1', phone_number = '99991')
	return redirect('index_page')

```

**Comment by brki** [comment]
Thanks @srikanth148.

Unfortunately at the moment CleanerVersion does not work with Django versions higher than 1.8.  There is an open pull request #127 for the DJANGO_1.9 branch, that needs to be reviewed and released.  (It's a pull request from the principal author of the project, so is probably quite trustworthy).

There probably are not too many changes that need to be made from the DJANGO_1.9 branch for it to work with Django 1.10, but I personally haven't investigated that yet.

I suppose we should ensure that pip refuses to install CleanerVersion for incompatible Django versions, I'll open a user story for that.

**Comment by srikanth148** [comment]
Thanks @brki

**Comment by maennel** [comment]
I guess this issue can be closed with PR #140. Closing. ;)
